# Generated by Django 5.1.2 on 2024-12-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=159, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=239, null=True, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
